apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
 bootstrapToken:
   token: "oi1cfc.tmryeaxmf3dreq66"
   apiServerEndpoint: "172.31.36.149:6443"
   caCertHashes:
     - "sha256:26a16b24d137975779d228fb3e34887d31aa5a12d398c631f91d95d43c863419"
nodeRegistration:
 name: ip-172-31-36-149.us-west-2.compute.internal
 kubeletExtraArgs:
   cloud-provider: aws

# kubeadm join --config /etc/kubernetes/node.yaml