- name: build docker image and push it to dockr hub
  hosts: localhost
  become: yes 
  become_user: ali
  

  tasks:
  - name: build image
    command: docker build -t reactjs-devops .
    args:
       chdir: /home/ali/devops/nginx

  - name: tag the image
    command: docker tag reactjs-devops abdelalidocker/reactjs-devops:latest


  - name: push the built image to dockerhub
    command: docker push abdelalidocker/reactjs-devops:latest


  - name: delete the built image and the taged one
    command: docker rmi reactjs-devops abdelalidocker/reactjs-devops:latest